[server]
listen-http-addr = "0.0.0.0:8080"
grpc-peer-addr = "0.0.0.0:8081"
api-token = "c362077ff38ef4c81b8278e91a956b2fd3c410b9a3906ac0f728813a2d3fb5fd"
use-h2c = true


[engine]
uvicorn-socket = false # 开启Unix Socket 模式减少TCP消耗资源
socket-path = "/app/uvicorn.sock"
#detect-ai-url = "http://unix/detect" # windows下容器访问识别程序地址 （）
detect-ai-url = "http://host.docker.internal:5000/detect" # windows下容器访问识别程序地址 （）
detect-host-status-url = "http://host.docker.internal:5000/host/status" # windows下容器访问识别程序地址 （）

healthy-heartbeat = 60
close-chan-cap = 128
push-url-internal-pre = "rtmp://rtmp-server/live"
push-url-public-pre = "rtmp://localhost:1935/live"
push-url-public-hls-pre = "http://localhost:1935"
pull-restart-mode = "hk"


[logger]
log-path = "./logs/detectLog"
log-level = "debug" #日志级别 全大写或全小写
split-max-size = 128
max-age = 30
max-backups = 100
local-time = true
compress = false



[redis]
host = "ai.lamdar.cn:19802"
password = "QpdUm3KNMXwya8Mjiuxiang"
max-idle-conns = 10
min-idle-conns = 5


[store]
session-end-channel-key = "session:end:channel"
detect-result-channel-key = "detect:result:channel"
record-video-channel-key = "record:video:channel"

record-path = "/app/recordings"
record-path-real = "/api/v1/lib/core/downloadFile?file=/recordings"

detect-result-path = "/app/detects"
detect-result-path-real = "/api/v1/lib/core/downloadFile?file=/detects"

[hk-video]
base-url = "https://183.215.46.57:1443/artemis"
app-key = "25373899"
app-secret = "E9TFZHKRNwsNOPbVFL6W"

[wvp-video]
base-url = "http://183.215.26.38:7011"
token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNlNzk2NDZjNGRiYzQwODM4M2E5ZWVkMDlmMmI4NWFlIn0.eyJqdGkiOiJsRmxrT1JLU18tWnV5Ti1GRVExRlpBIiwiaWF0IjoxNzQ1NDc0NDgwLCJleHAiOjE3NDgwNjY0ODAsIm5iZiI6MTc0NTQ3NDQ4MCwic3ViIjoibG9naW4iLCJhdWQiOiJBdWRpZW5jZSIsInVzZXJOYW1lIjoiYWRtaW4ifQ.NTWrJhnYjyXolnQyWJeT_dvXGmptQo9XemAMnrxbPVmj7xAHcbnb5Z9TF8VJ0uyU6zncq0ffbyBhdSUCvmgdJFe75Ww6AJHZI6R0o-4rqIrAT_KFqmVADFCBnZ-eAgJ99LhGsspHbEEsAchjTY-OV_IJIM9e-1TriGimcjKnZGtTvGNJrJ6lEXfVGRINjUm_Br_I49PVQ5N9mbFfjVBn5ZMEJj1hZlAWRANQ1MnESmCjjeFBkGYCcAUcVUqpQUUPj-kllB1OLZxjaM7XTeU7FC8uUcizB-7XFMXUdhynoU7jsyJhRqCG6akEPoaCgrnuP63NjJ3-U9nY0c66jpWXhA"