[server]
listen-http-addr = "0.0.0.0:8080"
grpc-peer-addr = "0.0.0.0:8081"

use-h2c = true


[engine]
uvicorn-socket = false # 开启Unix Socket 模式减少TCP消耗资源
socket-path = "/app/uvicorn.sock"
#detect-ai-url = "http://unix/detect" # windows下容器访问识别程序地址 （）
detect-ai-url = "http://host.docker.internal:5000/detect" # windows下容器访问识别程序地址 （）
healthy-heartbeat = 60
close-chan-cap = 128
push-url-internal-pre = "rtmp://rtmp-server/live"
push-url-public-pre = "rtmp://localhost:1935/live"
push-url-public-hls-pre = "http://localhost:1935"
pull-restart-mode = "hk"


[logger]
log-path = "./logs/detectLog"
log-level = "debug" #日志级别 全大写或全小写
split-max-size = 128
max-age = 30
max-backups = 100
local-time = true
compress = false



[redis]
host = "ai.lamdar.cn:19802"
password = "QpdUm3KNMXwya8Mjiuxiang"
max-idle-conns = 10
min-idle-conns = 5


[store]
detect-result-channel-key = "detect:result:channel"
record-video-channel-key = "record:video:channel"
record-path = "/app/recordings"
record-path-real = "/api/v1/lib/core/downloadFile?file=/recordings"

detect-result-path = "/app/detects"
detect-result-path-real = "/api/v1/lib/core/downloadFile?file=/detects"

[hk-video]
base-url = "https://183.215.46.57:1443/artemis"
app-key = "25373899"
app-secret = "E9TFZHKRNwsNOPbVFL6W"