// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: detect.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RtspURL    string `protobuf:"bytes,2,opt,name=rtspURL,proto3" json:"rtspURL,omitempty"`
	Width      int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height     int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Framerate  int32  `protobuf:"varint,5,opt,name=framerate,proto3" json:"framerate,omitempty"`
	RetryTimes int32  `protobuf:"varint,6,opt,name=retryTimes,proto3" json:"retryTimes,omitempty"`
}

func (x *CreateSessionReq) Reset() {
	*x = CreateSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionReq) ProtoMessage() {}

func (x *CreateSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionReq.ProtoReflect.Descriptor instead.
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionReq) GetRtspURL() string {
	if x != nil {
		return x.RtspURL
	}
	return ""
}

func (x *CreateSessionReq) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateSessionReq) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateSessionReq) GetFramerate() int32 {
	if x != nil {
		return x.Framerate
	}
	return 0
}

func (x *CreateSessionReq) GetRetryTimes() int32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

type SessionIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *SessionIDReq) Reset() {
	*x = SessionIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIDReq) ProtoMessage() {}

func (x *SessionIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIDReq.ProtoReflect.Descriptor instead.
func (*SessionIDReq) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{1}
}

func (x *SessionIDReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type SessionDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamKey     string `protobuf:"bytes,2,opt,name=streamKey,proto3" json:"streamKey,omitempty"`
	PushUrlPublic string `protobuf:"bytes,3,opt,name=pushUrlPublic,proto3" json:"pushUrlPublic,omitempty"`
	DetectStatus  bool   `protobuf:"varint,4,opt,name=detectStatus,proto3" json:"detectStatus,omitempty"` // 识别状态 false 停止 true 识别
}

func (x *SessionDesc) Reset() {
	*x = SessionDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDesc) ProtoMessage() {}

func (x *SessionDesc) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDesc.ProtoReflect.Descriptor instead.
func (*SessionDesc) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{2}
}

func (x *SessionDesc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionDesc) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *SessionDesc) GetPushUrlPublic() string {
	if x != nil {
		return x.PushUrlPublic
	}
	return ""
}

func (x *SessionDesc) GetDetectStatus() bool {
	if x != nil {
		return x.DetectStatus
	}
	return false
}

type GetSessionDescByIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists  bool         `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"` // 是否存在
	Session *SessionDesc `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *GetSessionDescByIDResp) Reset() {
	*x = GetSessionDescByIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionDescByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDescByIDResp) ProtoMessage() {}

func (x *GetSessionDescByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDescByIDResp.ProtoReflect.Descriptor instead.
func (*GetSessionDescByIDResp) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionDescByIDResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetSessionDescByIDResp) GetSession() *SessionDesc {
	if x != nil {
		return x.Session
	}
	return nil
}

type AllSessionDescResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sessions []*SessionDesc `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *AllSessionDescResp) Reset() {
	*x = AllSessionDescResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllSessionDescResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSessionDescResp) ProtoMessage() {}

func (x *AllSessionDescResp) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSessionDescResp.ProtoReflect.Descriptor instead.
func (*AllSessionDescResp) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{4}
}

func (x *AllSessionDescResp) GetSessions() []*SessionDesc {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GenericResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *GenericResp) Reset() {
	*x = GenericResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResp) ProtoMessage() {}

func (x *GenericResp) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResp.ProtoReflect.Descriptor instead.
func (*GenericResp) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{5}
}

func (x *GenericResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{6}
}

var File_detect_proto protoreflect.FileDescriptor

var file_detect_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x74, 0x73, 0x70, 0x55,
	0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x73, 0x70, 0x55, 0x52,
	0x4c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x2c, 0x0a,
	0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x85, 0x01, 0x0a, 0x0b,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x75, 0x73,
	0x68, 0x55, 0x72, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x75, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x5b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x73, 0x63, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x41, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x1d, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xdd, 0x02, 0x0a, 0x0d,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x33, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_detect_proto_rawDescOnce sync.Once
	file_detect_proto_rawDescData = file_detect_proto_rawDesc
)

func file_detect_proto_rawDescGZIP() []byte {
	file_detect_proto_rawDescOnce.Do(func() {
		file_detect_proto_rawDescData = protoimpl.X.CompressGZIP(file_detect_proto_rawDescData)
	})
	return file_detect_proto_rawDescData
}

var file_detect_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_detect_proto_goTypes = []any{
	(*CreateSessionReq)(nil),       // 0: pb.CreateSessionReq
	(*SessionIDReq)(nil),           // 1: pb.SessionIDReq
	(*SessionDesc)(nil),            // 2: pb.SessionDesc
	(*GetSessionDescByIDResp)(nil), // 3: pb.GetSessionDescByIDResp
	(*AllSessionDescResp)(nil),     // 4: pb.AllSessionDescResp
	(*GenericResp)(nil),            // 5: pb.GenericResp
	(*Empty)(nil),                  // 6: pb.Empty
}
var file_detect_proto_depIdxs = []int32{
	2, // 0: pb.GetSessionDescByIDResp.session:type_name -> pb.SessionDesc
	2, // 1: pb.AllSessionDescResp.sessions:type_name -> pb.SessionDesc
	0, // 2: pb.DetectService.CreateSession:input_type -> pb.CreateSessionReq
	6, // 3: pb.DetectService.GetAllSessionDesc:input_type -> pb.Empty
	1, // 4: pb.DetectService.GetSessionDescByID:input_type -> pb.SessionIDReq
	1, // 5: pb.DetectService.StopDetect:input_type -> pb.SessionIDReq
	1, // 6: pb.DetectService.ContinueDetect:input_type -> pb.SessionIDReq
	1, // 7: pb.DetectService.RemoveSession:input_type -> pb.SessionIDReq
	2, // 8: pb.DetectService.CreateSession:output_type -> pb.SessionDesc
	4, // 9: pb.DetectService.GetAllSessionDesc:output_type -> pb.AllSessionDescResp
	3, // 10: pb.DetectService.GetSessionDescByID:output_type -> pb.GetSessionDescByIDResp
	5, // 11: pb.DetectService.StopDetect:output_type -> pb.GenericResp
	5, // 12: pb.DetectService.ContinueDetect:output_type -> pb.GenericResp
	5, // 13: pb.DetectService.RemoveSession:output_type -> pb.GenericResp
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_detect_proto_init() }
func file_detect_proto_init() {
	if File_detect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_detect_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SessionIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SessionDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetSessionDescByIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AllSessionDescResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GenericResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detect_proto_goTypes,
		DependencyIndexes: file_detect_proto_depIdxs,
		MessageInfos:      file_detect_proto_msgTypes,
	}.Build()
	File_detect_proto = out.File
	file_detect_proto_rawDesc = nil
	file_detect_proto_goTypes = nil
	file_detect_proto_depIdxs = nil
}
